// <auto-generated />
using System;
using EindOpdracht.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EindOpdracht.Migrations
{
    [DbContext(typeof(EindOpdrachtDbContext))]
    [Migration("20240417173827_LastMigration")]
    partial class LastMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EindOpdracht.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("EindOpdracht.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCover")
                        .HasColumnType("bit");

                    b.Property<int?>("LandlordId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LandlordId")
                        .IsUnique()
                        .HasFilter("[LandlordId] IS NOT NULL");

                    b.HasIndex("LocationId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCover = false,
                            LocationId = 1,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/4/4c/160322-066_View_from_Thiri.jpg"
                        },
                        new
                        {
                            Id = 2,
                            IsCover = true,
                            LocationId = 2,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/b/bd/Broadway_Luxury_and_Eadburgha_House_-_geograph.org.uk_-_6093435.jpg"
                        },
                        new
                        {
                            Id = 25,
                            IsCover = false,
                            LocationId = 2,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/b/bd/Broadway_Luxury_and_Eadburgha_House_-_geograph.org.uk_-_6093435.jpg"
                        },
                        new
                        {
                            Id = 3,
                            IsCover = false,
                            LocationId = 3,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/9/95/President_Trump_Travels_to_Arizona_%2850041201672%29.jpg"
                        },
                        new
                        {
                            Id = 5,
                            IsCover = true,
                            LocationId = 1,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/4/4c/160322-066_View_from_Thiri.jpg"
                        },
                        new
                        {
                            Id = 6,
                            IsCover = true,
                            LocationId = 2,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/b/bd/Broadway_Luxury_and_Eadburgha_House_-_geograph.org.uk_-_6093435.jpg"
                        },
                        new
                        {
                            Id = 7,
                            IsCover = false,
                            LandlordId = 1,
                            LocationId = 1,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/3/34/Elon_Musk_Royal_Society_%28crop2%29.jpg"
                        },
                        new
                        {
                            Id = 8,
                            IsCover = false,
                            LandlordId = 2,
                            LocationId = 2,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Jeff_Bezos_2016_crop.jpg/640px-Jeff_Bezos_2016_crop.jpg"
                        },
                        new
                        {
                            Id = 9,
                            IsCover = false,
                            LandlordId = 3,
                            LocationId = 3,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/0/0b/Donald_Trump_%2852250930172%29_%28cropped%29.jpg"
                        },
                        new
                        {
                            Id = 10,
                            IsCover = true,
                            LocationId = 3,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/9/95/President_Trump_Travels_to_Arizona_%2850041201672%29.jpg"
                        },
                        new
                        {
                            Id = 11,
                            IsCover = true,
                            LocationId = 4,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/7/7e/Cricket_match_and_Marina_Bay_Sands_Hotel_in_Singapore.jpg"
                        },
                        new
                        {
                            Id = 12,
                            IsCover = false,
                            LocationId = 4,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/5/57/Singapore_%28SG%29%2C_ArtScience_Museum_and_Marina_Bay_Sands_Hotel_--_2019_--_4695.jpg"
                        },
                        new
                        {
                            Id = 13,
                            IsCover = true,
                            LocationId = 5,
                            Url = "https://www.nsrcc.com.sg/sites/nsrcc.d8.mx.sg/files/block-images/Home_Bungalow.jpg"
                        },
                        new
                        {
                            Id = 22,
                            IsCover = false,
                            LocationId = 5,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/5/57/Singapore_%28SG%29%2C_ArtScience_Museum_and_Marina_Bay_Sands_Hotel_--_2019_--_4695.jpg"
                        },
                        new
                        {
                            Id = 14,
                            IsCover = true,
                            LocationId = 6,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/1/14/Appartement_Chateau_Saint-Louis_04.jpg"
                        },
                        new
                        {
                            Id = 23,
                            IsCover = false,
                            LocationId = 6,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/5/57/Singapore_%28SG%29%2C_ArtScience_Museum_and_Marina_Bay_Sands_Hotel_--_2019_--_4695.jpg"
                        },
                        new
                        {
                            Id = 15,
                            IsCover = true,
                            LocationId = 7,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/f/fa/Trump_Tower_Entrance_2015-08.jpg"
                        },
                        new
                        {
                            Id = 24,
                            IsCover = false,
                            LocationId = 7,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/5/57/Singapore_%28SG%29%2C_ArtScience_Museum_and_Marina_Bay_Sands_Hotel_--_2019_--_4695.jpg"
                        },
                        new
                        {
                            Id = 16,
                            IsCover = true,
                            LocationId = 8,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/7/7e/Cricket_match_and_Marina_Bay_Sands_Hotel_in_Singapore.jpg"
                        },
                        new
                        {
                            Id = 17,
                            IsCover = false,
                            LocationId = 8,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/5/57/Singapore_%28SG%29%2C_ArtScience_Museum_and_Marina_Bay_Sands_Hotel_--_2019_--_4695.jpg"
                        },
                        new
                        {
                            Id = 18,
                            IsCover = true,
                            LocationId = 9,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/7/7e/Cricket_match_and_Marina_Bay_Sands_Hotel_in_Singapore.jpg"
                        },
                        new
                        {
                            Id = 19,
                            IsCover = false,
                            LocationId = 9,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/5/57/Singapore_%28SG%29%2C_ArtScience_Museum_and_Marina_Bay_Sands_Hotel_--_2019_--_4695.jpg"
                        },
                        new
                        {
                            Id = 20,
                            IsCover = true,
                            LocationId = 10,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/7/7e/Cricket_match_and_Marina_Bay_Sands_Hotel_in_Singapore.jpg"
                        },
                        new
                        {
                            Id = 21,
                            IsCover = false,
                            LocationId = 10,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/5/57/Singapore_%28SG%29%2C_ArtScience_Museum_and_Marina_Bay_Sands_Hotel_--_2019_--_4695.jpg"
                        });
                });

            modelBuilder.Entity("EindOpdracht.Models.Landlord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Landlords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            FirstName = "Koen",
                            LastName = "Hoeven"
                        },
                        new
                        {
                            Id = 2,
                            Age = 32,
                            FirstName = "Jan",
                            LastName = "Jansen"
                        },
                        new
                        {
                            Id = 3,
                            Age = 90,
                            FirstName = "Donald",
                            LastName = "Trumpet"
                        });
                });

            modelBuilder.Entity("EindOpdracht.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Features")
                        .HasColumnType("int");

                    b.Property<int?>("LandlordId")
                        .HasColumnType("int");

                    b.Property<int>("LocationType")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<float>("PricePerDay")
                        .HasColumnType("real");

                    b.Property<int>("Rooms")
                        .HasColumnType("int");

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LandlordId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "De camping ligt verscholen achter de boerderij in de polder. Op fietsafstand (5 minuten) liggen het dorpje Nieuwvliet, de zee, het strand, het bos van Erasmus en het natuurgebied de Knokkert.",
                            Features = 43,
                            LandlordId = 1,
                            LocationType = 1,
                            NumberOfGuests = 5,
                            PricePerDay = 500f,
                            Rooms = 5,
                            SubTitle = "Lekker veel ruimte",
                            Title = "De Boerenhoeve"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Nee, dit puike penthouse dat al jaren te koop stond en nu is verkocht, is niet de duurste woning van ons land. Bij lange na niet. Wel is de meer dan €30.000 per vierkante meter woonruimte een record in ons land.",
                            Features = 60,
                            LandlordId = 2,
                            LocationType = 5,
                            NumberOfGuests = 5,
                            PricePerDay = 2000f,
                            Rooms = 5,
                            SubTitle = "Te gek uitzicht",
                            Title = "Frankie's Penthouse"
                        },
                        new
                        {
                            Id = 3,
                            Description = "This powerful barrier is a vital step in securing our nation’s borders. By stopping illegal immigration, drugs, and crime, we are protecting the American people and upholding our laws. The Great American Wall stands as a symbol of strength, sovereignty, and the unwavering resolve of the United States to maintain its integrity and safety.",
                            Features = 3,
                            LandlordId = 3,
                            LocationType = 3,
                            NumberOfGuests = 5,
                            PricePerDay = 5f,
                            Rooms = 5,
                            SubTitle = "The Great American Wall",
                            Title = "Trump's Wall"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Marina Bay Sands is an iconic luxury hotel and entertainment complex in Singapore, renowned for its distinctive architecture featuring three interconnected towers and a SkyPark. The complex includes a range of amenities such as the world's largest rooftop infinity pool, a museum, high-end shopping, dining options, a casino, and an observation deck with panoramic views of the city.",
                            Features = 60,
                            LandlordId = 3,
                            LocationType = 4,
                            NumberOfGuests = 5,
                            PricePerDay = 600f,
                            Rooms = 2500,
                            SubTitle = "Luxury Hotel and Entertainment Complex",
                            Title = "Marina Bay Sands"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Nestled along the picturesque coastline of Singapore, NSRCC Chalets offer a tranquil escape within the National Service Resort & Country Club complex. These chalets are designed for comfort and relaxation, providing a perfect blend of leisure and activity. Guests can enjoy modern amenities, spacious accommodations, and direct access to extensive golfing facilities. The serene setting is enhanced by stunning views of lush greenery and the sea, making it an ideal location for family vacations, golf retreats, and private gatherings.",
                            Features = 1,
                            LandlordId = 1,
                            LocationType = 2,
                            NumberOfGuests = 5,
                            PricePerDay = 750f,
                            Rooms = 2500,
                            SubTitle = "Relaxing Retreat with Scenic Golf Views",
                            Title = "NSRCC Chalets: Serene Getaway by the Sea"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Harborview Residences offers a premium living experience in its modern apartment complex, strategically located to combine urban convenience with breathtaking views. This complex features a range of thoughtfully designed apartments that cater to diverse lifestyles, from bustling singles to growing families. Residents enjoy top-notch amenities including a fitness center, swimming pool, landscaped gardens, and a community clubhouse. The secure environment is complemented by easy access to local shopping, dining, and entertainment options, ensuring a balanced and vibrant lifestyle.",
                            Features = 1,
                            LandlordId = 2,
                            LocationType = 0,
                            NumberOfGuests = 5,
                            PricePerDay = 200f,
                            Rooms = 2500,
                            SubTitle = "Contemporary Apartments with Panoramic Cityscapes",
                            Title = "Harborview Residences: Modern Living Redefined"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Trump Tower stands as a symbol of luxury and power in the heart of New York City. This prestigious mixed-use skyscraper features a striking facade of reflective glass, housing 2500 rooms that include upscale residential units and corporate offices. The tower is known for its lavish interiors, including a six-story atrium adorned with pink marble and a 60-foot waterfall. Residents and visitors can enjoy first-rate amenities such as high-end shopping boutiques, fine dining restaurants, and exclusive access areas, all representing the pinnacle of urban opulence.",
                            Features = 1,
                            LandlordId = 3,
                            LocationType = 0,
                            NumberOfGuests = 5,
                            PricePerDay = 100f,
                            Rooms = 2500,
                            SubTitle = "Prestigious Residence and Business Hub",
                            Title = "Trump Tower: Urban Opulence Redefined"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Marina Bay Sands is an iconic luxury hotel and entertainment complex in Singapore, renowned for its distinctive architecture featuring three interconnected towers and a SkyPark. The complex includes a range of amenities such as the world's largest rooftop infinity pool, a museum, high-end shopping, dining options, a casino, and an observation deck with panoramic views of the city.",
                            Features = 1,
                            LandlordId = 2,
                            LocationType = 4,
                            NumberOfGuests = 5,
                            PricePerDay = 185f,
                            Rooms = 2500,
                            SubTitle = "Luxury Hotel and Entertainment Complex",
                            Title = "Marina Bay Sands"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Marina Bay Sands is an iconic luxury hotel and entertainment complex in Singapore, renowned for its distinctive architecture featuring three interconnected towers and a SkyPark. The complex includes a range of amenities such as the world's largest rooftop infinity pool, a museum, high-end shopping, dining options, a casino, and an observation deck with panoramic views of the city.",
                            Features = 1,
                            LandlordId = 1,
                            LocationType = 4,
                            NumberOfGuests = 5,
                            PricePerDay = 300f,
                            Rooms = 2500,
                            SubTitle = "Luxury Hotel and Entertainment Complex",
                            Title = "Marina Bay Sands"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Marina Bay Sands is an iconic luxury hotel and entertainment complex in Singapore, renowned for its distinctive architecture featuring three interconnected towers and a SkyPark. The complex includes a range of amenities such as the world's largest rooftop infinity pool, a museum, high-end shopping, dining options, a casino, and an observation deck with panoramic views of the city.",
                            Features = 24,
                            LandlordId = 1,
                            LocationType = 4,
                            NumberOfGuests = 2,
                            PricePerDay = 375f,
                            Rooms = 2500,
                            SubTitle = "Luxury Hotel and Entertainment Complex",
                            Title = "Marina Bay Sands"
                        });
                });

            modelBuilder.Entity("EindOpdracht.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<float>("Discount")
                        .HasColumnType("real");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LocationId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("EindOpdracht.Models.Image", b =>
                {
                    b.HasOne("EindOpdracht.Models.Landlord", "Landlord")
                        .WithOne("Avatar")
                        .HasForeignKey("EindOpdracht.Models.Image", "LandlordId");

                    b.HasOne("EindOpdracht.Models.Location", "Location")
                        .WithMany("Images")
                        .HasForeignKey("LocationId");

                    b.Navigation("Landlord");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("EindOpdracht.Models.Location", b =>
                {
                    b.HasOne("EindOpdracht.Models.Landlord", "Landlord")
                        .WithMany("Locations")
                        .HasForeignKey("LandlordId");

                    b.Navigation("Landlord");
                });

            modelBuilder.Entity("EindOpdracht.Models.Reservation", b =>
                {
                    b.HasOne("EindOpdracht.Models.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EindOpdracht.Models.Location", "Location")
                        .WithMany("Reservations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("EindOpdracht.Models.Customer", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("EindOpdracht.Models.Landlord", b =>
                {
                    b.Navigation("Avatar");

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("EindOpdracht.Models.Location", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
